Repository census-ecosystem/opencensus-go-exporter-stackdriver, pull requests merged in 2019-02, with the labels that each got.

#81 skip equality check for cached metric descriptor for built-in metrics.
  stats.go
Labels: cla: yes

#84 Integrate with core resource and known detectors
  resource.go
  resource_test.go
  stackdriver.go
  stats.go
Labels: cla: yes

#86 Add support for Float64 attribute.
  trace_proto.go
  trace_proto_test.go
Labels: cla: yes

#88 go.mod: update dependencies and tidy up
  go.mod
  go.sum
Labels: cla: yes

#90 Distinguish between gke_container and k8s_container monitored resource type
  monitoredresource/gcp_metadata_config.go
  monitoredresource/monitored_resources.go
  monitoredresource/monitored_resources_test.go
Labels: cla: yes

#89 add zero bucket if not present.
  equivalence_test.go
  metrics.go
  metrics_test.go
  stats.go
  stats_test.go
Labels: DO-NOT-MERGE, cla: yes

#93 Fix k8s_container resource labels.
  monitoredresource/monitored_resources.go
  monitoredresource/monitored_resources_test.go
Labels: bug, cla: yes
