Repository census-ecosystem/opencensus-go-exporter-stackdriver, pull requests merged in 2019-05, with the labels that each got.

#147 Update Google Cloud Go client version.
  go.mod
  go.sum
Labels: cla: yes

#148 Add opencensus_task labels to proto metrics if no default labels are provided.
  equivalence_test.go
  metrics_proto.go
  metrics_proto_test.go
Labels: bug, cla: yes

#149 Remove ocagent exporter dependency.
  equivalence_test.go
  go.mod
  go.sum
Labels: build, cla: yes, enhancement, test

#152 convert summary metrics to cumulatives and gauges.
  metrics_proto.go
  metrics_proto_test.go
Labels: cla: yes

#155 Fix resource mapping.
  go.mod
  go.sum
  resource.go
  resource_test.go
Labels: cla: yes

#158 transform resources for metrics exported via ExportMetricsProto api
  equivalence_test.go
  metrics_proto.go
  metrics_proto_test.go
  resource.go
  resource_test.go
Labels: cla: yes

#160 use container type instead of k8s type for resource transfomation
  go.mod
  go.sum
  metrics_proto_test.go
  resource.go
  resource_test.go
Labels: cla: yes
