Repository census-ecosystem/opencensus-go-exporter-stackdriver, pull requests merged in 2019-03, with the labels that each got.

#94 Remove instance-id label from k8s_container resource.
  monitoredresource/monitored_resources.go
  monitoredresource/monitored_resources_test.go
Labels: bug, cla: yes

#97 update .gitignore to exclude .idea
  .gitignore
Labels: cla: yes

#102 Upgrade oc-proto version and fix errors.
  equivalence_test.go
  go.mod
  go.sum
  metrics.go
  metrics_test.go
Labels: bug, cla: yes

#104 change ExportMetric api to ExportMetricProto
  equivalence_test.go
  metrics.go
  stackdriver.go
Labels: cla: yes

#105 Revert "change ExportMetric api to ExportMetricProto (#104)"
  equivalence_test.go
  metrics.go
  stackdriver.go
Labels: cla: yes

#106 Change ExportMetric api to ExportMetricProto
  equivalence_test.go
  metrics.go
  stackdriver.go
Labels: cla: yes

#107 rename metrics.go to metrics_proto.go.
  metrics_proto.go
  metrics_proto_test.go
  stats.go
Labels: cla: yes

#108 Fix metric descriptor convertion.
  equivalence_test.go
  metrics_proto.go
  metrics_proto_test.go
Labels: bug, cla: yes

#110 turn on go11 module
  .travis.yml
Labels: cla: yes

#111 Fix dependency issues when GO111MODULE is disabled.
  .travis.yml
  equivalence_test.go
  go.mod
  go.sum
Labels: cla: yes

#112 Remove exemplar for now.
  equivalence_test.go
  go.sum
Labels: build, cla: yes

#113 Update go.mod and go.sum.
  go.mod
  go.sum
Labels: build, cla: yes

#117 Fix an issue with multiple calls of Autodetec func
  monitoredresource/monitored_resources.go
Labels: cla: yes

#109 add support for exporting metrics data model
  metrics.go
  metrics_test.go
  stackdriver.go
  stats.go
Labels: cla: yes
