Repository census-ecosystem/opencensus-go-exporter-stackdriver, pull requests merged in 2019-04, with the labels that each got.

#119 Batch time series with different label values into same request.
  metrics_proto.go
  metrics_proto_test.go
  stats_test.go
Labels: cla: yes

#121 add Start and Stop function for metrics exporter.
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  stackdriver.go
  stats.go
Labels: cla: yes

#122 Use cmp instead of reflect and json in tests.
  equivalence_test.go
  metrics_proto_test.go
  metrics_test.go
  metrics_test_utils.go
Labels: cla: yes, test

#125 Upgrade dependencies in go.mod
  go.mod
  go.sum
Labels: build, cla: yes

#129 Update oc version in go.mod.
  go.mod
  go.sum
Labels: build, cla: yes

#132 Don't overwrite agent label if already set
  trace_proto.go
  trace_proto_test.go
Labels: cla: yes

#137 add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#139 Fix resource assignment in GKE and GCE environment when using metrics exporter.
  metrics.go
  metrics_test.go
Labels: DO-NOT-MERGE, cla: yes

#138 fix golint and add Makefile.
  .gitignore
  Makefile
  internal/testpb/impl.go
  metrics_test_utils.go
  resource.go
  resource_test.go
  stackdriver.go
  stats.go
Labels: cla: yes

#136 add support for label key description.
  go.mod
  go.sum
  metrics.go
Labels: cla: yes

#124 Support exporting Exemplar.
  metrics.go
  metrics_test.go
Labels: cla: yes

#142 Update dependency versions. Run go mod tidy.
  go.mod
  go.sum
Labels: cla: yes

#143 remove triage-me label from template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#146 Upgrade google cloud go client version.
  go.mod
  go.sum
Labels: cla: yes
